using Microsoft.EntityFrameworkCore;
using QazaqQuest.Data;

namespace QazaqQuest.Services;

public static class DatabaseInitializer
{
    public static void EnsureSchema(AppDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw(@"
CREATE TABLE IF NOT EXISTS ""Quests"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Title"" character varying(200) NOT NULL,
    ""Description"" text NOT NULL,
    ""City"" character varying(100) NOT NULL,
    ""Difficulty"" character varying(50) NOT NULL,
    ""Type"" character varying(50) NOT NULL,
    ""Price"" numeric(18,2) NOT NULL,
    ""Duration"" text NOT NULL,
    ""RouteLength"" text NOT NULL,
    ""Category"" text NOT NULL,
    ""Audience"" text NOT NULL,
    ""ImageUrl"" character varying(500) NOT NULL,
    ""CoverStyle"" character varying(300) NOT NULL,
    ""Icon"" character varying(20) NOT NULL,
    ""Language"" text NOT NULL,
    ""Partner"" text NOT NULL,
    ""Bonus"" text NOT NULL
);

CREATE TABLE IF NOT EXISTS ""QuestLocations"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""QuestId"" integer NOT NULL REFERENCES ""Quests""(""Id"") ON DELETE CASCADE,
    ""Name"" character varying(200) NOT NULL,
    ""Address"" character varying(300) NOT NULL,
    ""Latitude"" double precision NOT NULL,
    ""Longitude"" double precision NOT NULL,
    ""RadiusMeters"" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS ""QuestPoints"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""QuestId"" integer NOT NULL REFERENCES ""Quests""(""Id"") ON DELETE CASCADE,
    ""QuestLocationId"" integer NULL REFERENCES ""QuestLocations""(""Id"") ON DELETE SET NULL,
    ""Name"" character varying(200) NOT NULL,
    ""Task"" text NOT NULL,
    ""Answer"" character varying(200) NOT NULL,
    ""TaskType"" character varying(100) NOT NULL,
    ""Hint"" character varying(500) NOT NULL,
    ""Options"" text NOT NULL,
    ""Latitude"" double precision NOT NULL DEFAULT 0,
    ""Longitude"" double precision NOT NULL DEFAULT 0,
    ""RadiusMeters"" integer NOT NULL DEFAULT 0,
    ""Order"" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS ""Rewards"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""QuestId"" integer NOT NULL REFERENCES ""Quests""(""Id"") ON DELETE CASCADE,
    ""Title"" character varying(200) NOT NULL,
    ""Description"" text NOT NULL,
    ""Points"" integer NOT NULL
);
");
    }
}