using Microsoft.EntityFrameworkCore;
using QazaqQuest.Data;

namespace QazaqQuest.Services;

public static class DatabaseInitializer
{
    public static void EnsureSchema(AppDbContext dbContext)
    {
        dbContext.Database.ExecuteSqlRaw("""
CREATE TABLE IF NOT EXISTS "Quests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "City" character varying(100) NOT NULL,
    "Difficulty" character varying(50) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Duration" text NOT NULL,
    "RouteLength" text NOT NULL,
    "Category" text NOT NULL,
    "Audience" text NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "CoverStyle" character varying(300) NOT NULL,
    "Icon" character varying(20) NOT NULL,
    "Language" text NOT NULL,
    "Partner" text NOT NULL,
    "Bonus" text NOT NULL,
    "IsHidden" boolean NOT NULL DEFAULT FALSE,
    "IsTimed" boolean NOT NULL DEFAULT FALSE,
    "IsCoop" boolean NOT NULL DEFAULT FALSE,
    "IsFeatured" boolean NOT NULL DEFAULT FALSE,
    "UnlockLevel" integer NOT NULL DEFAULT 1,
    "TimeLimitMinutes" integer NOT NULL DEFAULT 0,
    "ExperienceReward" integer NOT NULL DEFAULT 100,
    "CoinsReward" integer NOT NULL DEFAULT 25
);

CREATE TABLE IF NOT EXISTS "QuestLocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestId" integer NOT NULL REFERENCES "Quests"("Id") ON DELETE CASCADE,
    "Name" character varying(200) NOT NULL,
    "Address" character varying(300) NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "RadiusMeters" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "QuestPoints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestId" integer NOT NULL REFERENCES "Quests"("Id") ON DELETE CASCADE,
    "QuestLocationId" integer NULL REFERENCES "QuestLocations"("Id") ON DELETE SET NULL,
    "Name" character varying(200) NOT NULL,
    "Task" text NOT NULL,
    "Answer" character varying(200) NOT NULL,
    "TaskType" character varying(100) NOT NULL,
    "Hint" character varying(500) NOT NULL,
    "Options" text NOT NULL,
    "Latitude" double precision NOT NULL DEFAULT 0,
    "Longitude" double precision NOT NULL DEFAULT 0,
    "RadiusMeters" integer NOT NULL DEFAULT 0,
    "Order" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "Rewards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestId" integer NOT NULL REFERENCES "Quests"("Id") ON DELETE CASCADE,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Points" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "UserQuestProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "QuestId" integer NOT NULL REFERENCES "Quests"("Id") ON DELETE CASCADE,
    "CurrentStep" integer NOT NULL DEFAULT 0,
    "TotalSteps" integer NOT NULL DEFAULT 0,
    "IsCompleted" boolean NOT NULL DEFAULT FALSE,
    "IsHiddenUnlocked" boolean NOT NULL DEFAULT FALSE,
    "IsRewardClaimed" boolean NOT NULL DEFAULT FALSE,
    "AttemptsCount" integer NOT NULL DEFAULT 0,
    "StartedAtUtc" timestamp without time zone NOT NULL,
    "CompletedAtUtc" timestamp without time zone NULL,
    "LastPlayedAtUtc" timestamp without time zone NULL,
    UNIQUE ("UserId", "QuestId")
);

CREATE TABLE IF NOT EXISTS "UserAchievements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Code" character varying(120) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "RewardPoints" integer NOT NULL DEFAULT 0,
    "UnlockedAtUtc" timestamp without time zone NOT NULL,
    UNIQUE ("UserId", "Code")
);

ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "AvatarUrl" character varying(500) NOT NULL DEFAULT '';
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ExperiencePoints" integer NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "Coins" integer NOT NULL DEFAULT 0;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "Level" integer NOT NULL DEFAULT 1;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "IsHidden" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "IsTimed" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "IsCoop" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "IsFeatured" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "UnlockLevel" integer NOT NULL DEFAULT 1;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "TimeLimitMinutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "ExperienceReward" integer NOT NULL DEFAULT 100;
ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "CoinsReward" integer NOT NULL DEFAULT 25;


CREATE TABLE IF NOT EXISTS "DailyChallenges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "ChallengeType" character varying(100) NOT NULL,
    "TargetValue" integer NOT NULL DEFAULT 1,
    "ExperienceReward" integer NOT NULL DEFAULT 0,
    "CoinsReward" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "ActiveDateUtc" timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "DailyChallengeProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DailyChallengeId" integer NOT NULL REFERENCES "DailyChallenges"("Id") ON DELETE CASCADE,
    "UserId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "CurrentValue" integer NOT NULL DEFAULT 0,
    "IsCompleted" boolean NOT NULL DEFAULT FALSE,
    "IsRewardClaimed" boolean NOT NULL DEFAULT FALSE,
    "CreatedAtUtc" timestamp without time zone NOT NULL,
    "CompletedAtUtc" timestamp without time zone NULL,
    UNIQUE ("UserId", "DailyChallengeId")
);

CREATE TABLE IF NOT EXISTS "Friendships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RequesterId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "AddresseeId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "Status" character varying(40) NOT NULL,
    "CreatedAtUtc" timestamp without time zone NOT NULL,
    "AcceptedAtUtc" timestamp without time zone NULL,
    UNIQUE ("RequesterId", "AddresseeId")
);

CREATE TABLE IF NOT EXISTS "ChatMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SenderId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "RecipientId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "MessageText" character varying(1500) NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "SentAtUtc" timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "QuestReviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "QuestId" integer NOT NULL REFERENCES "Quests"("Id") ON DELETE CASCADE,
    "UserId" uuid NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Rating" integer NOT NULL,
    "Comment" character varying(1500) NOT NULL,
    "CreatedAtUtc" timestamp without time zone NOT NULL,
    UNIQUE ("UserId", "QuestId")
);
""");
    }
}
